'use client'

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es';

interface Translations {
  [key: string]: {
    en: string;
    es: string;
  };
}

export const translations: Translations = {
  // Home Page
  hero_title: { en: 'One trip, a thousand destinations.', es: 'Un viaje, mil destinos.' },
  hero_subtitle: { en: 'Why stay with only one city? Discover several in the same trip and make the most of your vacation.', es: '¿Por qué quedarte solo con una ciudad? Descubre varias en un mismo viaje y aprovecha al máximo tus vacaciones.' },
  hero_btn: { en: 'View Recommended Routes', es: 'Ver rutas recomendadas' },
  hero_btn_design: { en: 'Design Your Trip', es: 'Diseña tu viaje' },
  form_title: { en: 'Build Your Dream Trip', es: 'Crea el Viaje de tus Sueños' },
  popular_title: { en: 'Popular Itineraries', es: 'Itinerarios Populares' },
  popular_subtitle: { en: 'Hand-picked experiences generated by our community', es: 'Experiencias seleccionadas generadas por nuestra comunidad' },
  view_all: { en: 'View More', es: 'Ver Más' },
  popular_days: { en: 'Days', es: 'Días' },
  card_price_from: { en: 'From', es: 'Desde' },
  card_popular: { en: 'Popular', es: 'Popular' },
  card_culture: { en: 'Culture', es: 'Cultura' },
  card_luxury: { en: 'Luxury', es: 'Lujo' },
  card_explore: { en: 'Explore', es: 'Explorar' },

  // Header
  nav_explore: { en: 'Explore', es: 'Explorar' },
  nav_discover: { en: 'Discover', es: 'Descubrir' },
  nav_my_trips: { en: 'My Trips', es: 'Mis Viajes' },
  btn_login: { en: 'Login', es: 'Iniciar Sesión' },
  btn_signup: { en: 'Sign Up', es: 'Registrarse' },
  
  // Footer
  footer_rights: { en: 'All rights reserved.', es: 'Todos los derechos reservados.' },
  footer_built_with: { en: 'Built with intelligence for the curious traveler.', es: 'Creado con inteligencia para el viajero curioso.' },
  footer_destinations: { en: 'Destinations', es: 'Destinos' },
  footer_budget_trips: { en: 'Budget Trips', es: 'Viajes Económicos' },
  footer_luxury_stays: { en: 'Luxury Stays', es: 'Estancias de Lujo' },
  footer_support: { en: 'Support', es: 'Soporte' },
  
  // Form
  form_origin: { en: 'Origin', es: 'Origen' },
  form_destination: { en: 'Destination', es: 'Destino' },
  form_origin_placeholder: { en: 'City or Airport', es: 'Ciudad o Aeropuerto' },
  form_destination_placeholder: { en: 'Where to?', es: '¿A dónde vas?' },
  form_transport: { en: 'Transport Type', es: 'Tipo de Transporte' },
  form_plane: { en: 'Plane', es: 'Avión' },
  form_car: { en: 'Car', es: 'Coche' },
  form_travelers: { en: 'Travelers', es: 'Viajeros' },
  form_duration: { en: 'Duration', es: 'Duración' },
  form_budget: { en: 'Budget Range', es: 'Rango de Presupuesto' },
  form_style: { en: 'Travel Style', es: 'Estilo de Viaje' },
  form_interests: { en: 'Interests', es: 'Intereses' },
  form_btn_generate: { en: 'Generate Itinerary', es: 'Generar Itinerario' },
  form_loading: { en: 'Generating...', es: 'Generando...' },
  form_error: { en: 'Something went wrong. Please try again.', es: 'Ocurrió un error. Por favor, inténtalo de nuevo.' },
  error_destination: { en: 'Please enter a destination', es: 'Por favor, introduce un destino' },
  
  // Travel Styles
  tour_cultural: { en: 'Cultural Immersion', es: 'Inmersión Cultural' },
  tour_gastronomic: { en: 'Gastronomic Tour', es: 'Tour Gastronómico' },
  tour_nature: { en: 'Nature & Wildlife', es: 'Naturaleza y Fauna' },
  tour_adventure: { en: 'Adventure Sports', es: 'Deportes de Aventura' },
  tour_road_trip: { en: 'Road Trip', es: 'Viaje por Carretera' },
  tour_explorer: { en: 'Explorer', es: 'Explorador' },
  tour_relaxed: { en: 'Relaxed Travel', es: 'Viaje Relajado' },
  tour_weekend: { en: 'Weekend Escape', es: 'Escapada de Fin de Semana' },

  // Durations
  dur_weekend: { en: 'Weekend (2-3 days)', es: 'Fin de Semana (2-3 días)' },
  dur_3_5: { en: '3-5 Days', es: '3-5 Días' },
  dur_1_week: { en: '1 Week', es: '1 Semana' },
  dur_2_weeks: { en: '2+ Weeks', es: '2+ Semanas' },

  // Travelers
  trav_solo: { en: 'Solo Traveler', es: 'Viajero Solitario' },
  trav_couple: { en: 'Couple', es: 'Pareja' },
  trav_family: { en: 'Family (3-5)', es: 'Familia (3-5)' },
  trav_group: { en: 'Group (6+)', es: 'Grupo (6+)' },

  // Budget
  budget_low: { en: 'Economy', es: 'Económico' },
  budget_high: { en: 'Luxury', es: 'Lujo' },

  // Interests (mapping keys from form)
  interest_hiking: { en: 'Hiking', es: 'Senderismo' },
  interest_cycling: { en: 'Cycling', es: 'Ciclismo' },
  interest_photography: { en: 'Photography', es: 'Fotografía' },
  interest_scenic_viewpoints: { en: 'Scenic Viewpoints', es: 'Miradores' },
  interest_historic_towns: { en: 'Historic Towns', es: 'Pueblos Históricos' },
  interest_gastronomy: { en: 'Gastronomy', es: 'Gastronomía' },
  interest_beaches: { en: 'Beaches', es: 'Playas' },
  interest_nature: { en: 'Nature', es: 'Naturaleza' },
  
  // Itinerary Page
  loading_searching: { en: 'Searching...', es: 'Buscando...' },
  loading_expert: { en: 'Contacting local travel experts...', es: 'Conectando con expertos locales...' },
  loading_gems: { en: 'Searching for hidden gems...', es: 'Buscando rincones emblemáticos...' },
  loading_routes: { en: 'Optimizing travel routes...', es: 'Optimizando rutas de transporte...' },
  loading_curating: { en: 'Curating personal experiences...', es: 'Personalizando tus experiencias...' },
  loading_finalizing: { en: 'Finalizing your perfect trip...', es: 'Finalizando tu viaje perfecto...' },
  
  // Itinerary Page
  loading_itinerary: { en: 'Translating itinerary...', es: 'Traduciendo itinerario...' },
  trip_not_found: { en: 'Itinerary not found', es: 'Itinerario no encontrado' },
  trip_not_found_desc: { en: 'We could not retrieve your trip. Please ensure you have generated one using the form.', es: 'No hemos podido recuperar tu viaje. Asegúrate de haber completado el formulario de generación.' },
  generate_new_btn: { en: 'Please generate a new itinerary', es: 'Por favor, genera un nuevo itinerario' },
  back_home: { en: 'Go Home', es: 'Volver al Inicio' },
  road_trip_msg: { en: 'Road Trip', es: 'Viaje por Carretera' },
  day_label: { en: 'Day', es: 'Día' },
  tips_label: { en: 'Travel Tips', es: 'Consejos de Viaje' },
  hours_unit: { en: 'hours', es: 'horas' },
  budget_breakdown: { en: 'Budget Breakdown', es: 'Desglose de Presupuesto' },
  type_activity_label: { en: 'Activity', es: 'Actividad' },
  type_restaurant_label: { en: 'Restaurant', es: 'Restaurante' },
  type_hotel_label: { en: 'Hotel', es: 'Hotel' },
  details_btn: { en: 'Details', es: 'Detalles' },
  reserve_btn: { en: 'Reserve', es: 'Reservar' },
  search_google_btn: { en: 'Search on Google', es: 'Explorar en Google' },
  confirm_reserve_title: { en: 'Confirm Reservation', es: 'Confirmar Reserva' },
  location_label: { en: 'Location', es: 'Ubicación' },
  rating_label: { en: 'Rating', es: 'Valoración' },
  cost_label: { en: 'Cost', es: 'Gasto' },
  schedule_label: { en: 'Schedule', es: 'Horario' },
  free_label: { en: 'Free', es: 'Gratis' },
  
  // Place Rich Details
  place_info: { en: 'Information', es: 'Información' },
  place_website: { en: 'Website', es: 'Sitio Web' },
  place_call: { en: 'Call', es: 'Llamar' },
  place_directions: { en: 'Directions', es: 'Cómo llegar' },
  place_hours: { en: 'Opening Hours', es: 'Horarios' },
  place_open: { en: 'Open Now', es: 'Abierto' },
  place_closed: { en: 'Closed', es: 'Cerrado' },
  
  // Timeline Markers
  type_visit: { en: 'VISIT', es: 'VISITA' },
  type_gastronomy: { en: 'GASTRONOMY', es: 'GASTRONOMÍA' },
  type_lodging: { en: 'LODGING', es: 'ALOJAMIENTO' },
  type_walk: { en: 'WALK', es: 'PASEO' },
  type_transport: { en: 'TRANSPORT', es: 'TRANSPORTE' },
  
  // Budget Panel
  budget_total: { en: 'Total Estimated', es: 'Total Estimado' },
  budget_estimated_total: { en: 'Total Estimated Budget', es: 'Presupuesto Total Estimado' },
  budget_activities: { en: 'Activities', es: 'Actividades' },
  budget_food: { en: 'Food & Drink', es: 'Comida y Bebida' },
  budget_transport: { en: 'Transport', es: 'Transporte' },
  budget_estimation: { en: 'Budget Estimation', es: 'Estimación de Presupuesto' },
  budget_based_on_items: { en: 'Based on itinerary items', es: 'Basado en los elementos del itinerario' },
  
  // Loading Messages
  loading_msg_1: { en: 'Contacting local travel experts...', es: 'Conectando con expertos locales...' },
  loading_msg_2: { en: 'Searching for hidden gems...', es: 'Buscando rincones emblemáticos...' },
  loading_msg_3: { en: 'Optimizing travel routes...', es: 'Optimizando rutas de transporte...' },
  loading_msg_4: { en: 'Curating personal experiences...', es: 'Personalizando tus experiencias...' },
  loading_msg_5: { en: 'Finalizing your perfect trip...', es: 'Finalizando tu viaje perfecto...' },
  loading_status: { en: 'Analyzing', es: 'Analizando Datos' },
  
  // Discover Page
  disc_title: { en: 'Discover Your Next Adventure', es: 'Descubre tu Próxima Aventura' },
  disc_subtitle: { en: 'Explore our curated selection of global destinations and start your journey with a single click.', es: 'Explora nuestra selección de destinos globales y empieza tu viaje con un solo clic.' },
  disc_origin: { en: 'Origin City', es: 'Ciudad de Origen' },
  disc_origin_placeholder: { en: 'e.g. London, UK', es: 'ej. Madrid, España' },
  disc_budget: { en: 'Budget (€)', es: 'Presupuesto (€)' },
  disc_days: { en: 'Days', es: 'Días' },
  disc_btn_discover: { en: 'Discover', es: 'Descubrir' },
  disc_searching: { en: 'Searching...', es: 'Buscando...' },
  disc_recommended: { en: 'Recommended for You', es: 'Recomendado para ti' },
  disc_generate_full: { en: 'Generate Full Itinerary', es: 'Generar Itinerario Completo' },
  disc_empty: { en: 'Enter details above to discover destinations!', es: '¡Introduce los detalles arriba para descubrir destinos!' },
  disc_mode: { en: 'Discovery Mode', es: 'Modo Descubrimiento' },

  // New translations
  form_arrival_time: { en: 'Arrival Time', es: 'Hora de llegada' },
  form_departure_time: { en: 'Departure Time', es: 'Hora de salida' },
  iti_transport: { en: 'Transport', es: 'Transporte' },
  iti_gasto_dia: { en: 'DAILY BUDGET', es: 'GASTO DÍA' },
  iti_total_budget: { en: 'Total Budget', es: 'Gasto Total' },
  
  // Popular Itineraries (HomePage)
  pop_amalfi_title: { en: 'Coastal Wonders', es: 'Maravillas Costeras' },
  pop_amalfi_loc: { en: 'Amalfi Coast, Italy', es: 'Costa Amalfitana, Italia' },
  pop_amalfi_desc: { en: 'Explore picturesque villages perched on cliffs and enjoy Mediterranean cuisine under the sun.', es: 'Explora pueblos pintorescos colgados de acantilados y disfruta la gastronomía mediterránea bajo el sol.' },
  pop_amalfi_dur: { en: '1 week', es: '1 semana' },
  
  pop_kyoto_title: { en: 'Temple Route', es: 'Ruta de los Templos' },
  pop_kyoto_loc: { en: 'Kyoto, Japan', es: 'Kioto, Japón' },
  pop_kyoto_desc: { en: 'Immerse yourself in the serenity of Zen gardens and the elegance of geishas in the Gion district.', es: 'Sumérgete en la serenidad de los jardines Zen y la elegancia de las geishas en el barrio de Gion.' },
  pop_kyoto_dur: { en: '5 days', es: '5 días' },
  
  pop_santorini_title: { en: 'Cycladic Odyssey', es: 'Odisea Cicládica' },
  pop_santorini_loc: { en: 'Santorini, Greece', es: 'Santorini, Grecia' },
  pop_santorini_desc: { en: 'Gaze at the world\'s most famous sunsets between blue domes and the infinite blue of the Aegean.', es: 'Contempla los atardeceres más famosos del mundo entre cúpulas azules y el azul infinito del Egeo.' },
  pop_santorini_dur: { en: '10 days', es: '10 días' },
  
  form_engine_subtitle: { en: 'TRIPS DESIGNED BY AI ENGINE', es: 'VIAJES DISEÑADOS POR MOTOR DE IA' },
  
  // Schedule types
  type_lunch: { en: 'LUNCH', es: 'COMIDA' },
  type_dinner: { en: 'DINNER', es: 'CENA' },

  // Form errors
  err_no_destination: { en: 'Please enter a destination.', es: 'Por favor, indica un destino.' },
  err_no_destination_first: { en: 'Enter a destination first.', es: 'Indica un destino primero.' },
  err_timeout: { en: 'Request timed out. Please try again.', es: 'Superado tiempo de espera. Reintenta.' },
  err_server: { en: 'Server error (invalid format). Please try again.', es: 'Error del servidor (formato inválido). Inténtalo de nuevo.' },

  // Discover Page Destinations
  dest1_title: { en: 'Parisian Elegance', es: 'Elegancia Parisina' },
  dest1_loc: { en: 'Paris, France', es: 'París, Francia' },
  dest2_title: { en: 'New York Pulse', es: 'Pulso Neoyorquino' },
  dest2_loc: { en: 'New York, USA', es: 'Nueva York, EE.UU.' },
  dest3_title: { en: 'Roman History', es: 'Historia Romana' },
  dest3_loc: { en: 'Rome, Italy', es: 'Roma, Italia' },
  dest4_title: { en: 'Neon Tokyo', es: 'Tokio Neón' },
  dest4_loc: { en: 'Tokyo, Japan', es: 'Tokio, Japón' },
  dest5_title: { en: 'Barcelona Vibes', es: 'Vibras de Barcelona' },
  dest5_loc: { en: 'Barcelona, Spain', es: 'Barcelona, España' },
  dest6_title: { en: 'London Heritage', es: 'Herencia Londinense' },
  dest6_loc: { en: 'London, UK', es: 'Londres, Reino Unido' },
  dest7_title: { en: 'Alpine Escape', es: 'Escape en los Alpes' },
  dest7_loc: { en: 'Zermatt, Switzerland', es: 'Zermatt, Suiza' },
  dest8_title: { en: 'Iceland Wonders', es: 'Maravillas de Islandia' },
  dest8_loc: { en: 'Reykjavik, Iceland', es: 'Reikiavik, Islandia' },
  dest9_title: { en: 'Zen in Bali', es: 'Zen en Bali' },
  dest9_loc: { en: 'Ubud, Indonesia', es: 'Ubud, Indonesia' },
  dest10_title: { en: 'Greek Islands', es: 'Islas Griegas' },
  dest10_loc: { en: 'Santorini, Greece', es: 'Santorini, Grecia' },
  dest11_title: { en: 'Moroccan Spices', es: 'Especias de Marruecos' },
  dest11_loc: { en: 'Marrakech, Morocco', es: 'Marrakech, Marruecos' },
  dest12_title: { en: 'Amsterdam Canals', es: 'Canales de Ámsterdam' },
  dest12_loc: { en: 'Amsterdam, Netherlands', es: 'Ámsterdam, Países Bajos' }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang) setLanguage(savedLang);
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string) => {
    const translation = translations[key];
    if (!translation) return key;
    return translation[language];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
