import TravelForm from '@/components/forms/TravelForm'
import Card from '@/components/ui/Card'
import Badge from '@/components/ui/Badge'
import Link from 'next/link'

const popularItineraries = [
  {
    id: 'amalfi-coast-7-days',
    title: 'Amalfi Coast Wonders',
    location: 'Amalfi Coast, Italy',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&q=80',
    duration: 7,
    type: 'cultural',
    rating: 4.9,
    reviews: 234,
  },
  {
    id: 'kyoto-5-days',
    title: 'Kyoto Temple Trail',
    location: 'Kyoto, Japan',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    duration: 5,
    type: 'cultural',
    rating: 4.8,
    reviews: 189,
  },
  {
    id: 'santorini-10-days',
    title: 'Cycladic Odyssey',
    location: 'Santorini, Greece',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    duration: 10,
    type: 'island',
    rating: 5.0,
    reviews: 312,
  },
]

export default function HomePage() {
  return (
    <>
      <section className="relative h-[500px] w-full overflow-hidden">
        <div 
          className="absolute inset-0 bg-cover bg-center"
          style={{
            backgroundImage: `linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.6)), url('https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&q=80')`,
          }}
        />
        <div className="relative h-full flex flex-col items-center justify-center text-center px-6">
          <h1 className="text-5xl md:text-7xl font-black text-white mb-6 tracking-tight">
            Escape the Ordinary
          </h1>
          <p className="text-lg md:text-xl text-white/90 max-w-2xl mb-8 leading-relaxed">
            Your personal AI concierge for crafting unforgettable journeys. No more endless searching, just pure exploration.
          </p>
          <Link 
            href="#planning-form"
            className="bg-primary hover:scale-105 transform transition-all text-white px-8 py-4 rounded-xl font-bold text-lg shadow-xl shadow-primary/20"
          >
            Start Your Journey
          </Link>
        </div>
      </section>

      <section id="planning-form" className="container mx-auto px-6 -mt-20 relative z-10 pb-20">
        <div className="bg-white dark:bg-slate-900 rounded-xl shadow-2xl p-8 border border-slate-100 dark:border-slate-800">
          <div className="flex items-center gap-3 mb-8">
            <span className="material-symbols-outlined text-primary p-2 bg-primary/10 rounded-lg">map</span>
            <h2 className="text-2xl font-bold">Build Your Dream Trip</h2>
          </div>
          <TravelForm />
        </div>
      </section>

      <section className="container mx-auto px-6 py-20">
        <div className="flex items-center justify-between mb-12">
          <div>
            <h2 className="text-3xl font-black tracking-tight mb-2">Popular Itineraries</h2>
            <p className="text-slate-500 dark:text-slate-400">Hand-picked experiences generated by our community</p>
          </div>
          <Link href="/discover" className="text-primary font-bold flex items-center gap-1 hover:underline">
            View All <span className="material-symbols-outlined">chevron_right</span>
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {popularItineraries.map((itinerary) => (
            <Link key={itinerary.id} href={`/itinerary/${itinerary.id}`}>
              <Card variant="hover" className="overflow-hidden group">
                <div className="relative h-56 overflow-hidden">
                  <img
                    src={itinerary.image}
                    alt={itinerary.title}
                    className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
                  />
                  <div className="absolute top-4 left-4">
                    <Badge variant="primary">{itinerary.type}</Badge>
                  </div>
                </div>
                <div className="p-6">
                  <h3 className="text-xl font-bold mb-2">{itinerary.title}</h3>
                  <p className="text-slate-500 dark:text-slate-400 text-sm mb-4 line-clamp-2">
                    {itinerary.location}
                  </p>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-1 text-primary">
                      <span className="material-symbols-outlined text-sm">schedule</span>
                      <span className="text-xs font-bold uppercase tracking-wider">{itinerary.duration} Days</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <span className="material-symbols-outlined text-yellow-400 text-sm">star</span>
                      <span className="text-sm font-bold">{itinerary.rating}</span>
                    </div>
                  </div>
                </div>
              </Card>
            </Link>
          ))}
        </div>
      </section>
    </>
  )
}
